apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress-chart.fullname" . }}-wordpress
spec:
  replicas: {{ .Values.wordpress.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "wordpress-chart.name" . }}-wordpress
  template:
    metadata:
      labels:
        app: {{ include "wordpress-chart.name" . }}-wordpress
    spec:
      containers:
        - name: wordpress
          image: "{{ .Values.wordpress.image.repository }}:{{ .Values.wordpress.image.tag }}"
          imagePullPolicy: {{ .Values.wordpress.image.pullPolicy }}
          env:
            - name: WORDPRESS_DB_HOST
              value: "{{ include "wordpress-chart.fullname" . }}-mysql:3306"
            - name: WORDPRESS_DB_USER
              value: "{{ .Values.mysql.user }}"
            - name: WORDPRESS_DB_PASSWORD
              value: "{{ .Values.mysql.password }}"
            - name: WORDPRESS_DB_NAME
              value: "{{ .Values.mysql.database }}"
          ports:
            - containerPort: 80

